modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/incubation/issues"
[[mods]]
modId="incubation"
version="1.0.1"
displayName="Incubation"
displayURL="https://www.curseforge.com/minecraft/mc-mods/incubation"
logoFile="logo.png"
credits="Markus1002"
authors="Markus1002"
description='''Adds chicken nests and makes eggs more useful.'''
[[dependencies.incubation]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incubation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
