modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/incubation/issues"
[[mods]]
modId="incubation"
version="1.0.4"
displayName="Incubation"
displayURL="https://www.curseforge.com/minecraft/mc-mods/incubation"
logoFile="logo.png"
credits="Markus1002, Translators: vhslance, F4zzer, peehpeh"
authors="Markus1002"
description='''Adds chicken nests and makes eggs more useful.'''
[[dependencies.incubation]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incubation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
